# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af72aa615605f82f4ac6694eb675e6e2d75dfdf14c1bd55cbd763bf5b8be6a562545c3f301a375536ba6766a99a054fd9e836d6586e5277095bea89d00d334a6

test:
  secret_key_base: 242b47c6ca60f83a7e0099a359efa6490d1117c9157cafd25dd0a9186f9e192646a324ad7f9cca8139e375527840e17d7e71eb887fa6d93af41b6052eddcdf0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
