# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f212ab927b4a45f2201c504f8583cb586aaab8bab2a2122585dcf92dbc45378d06ad2f7a19934f202f9b5b72e619583ed5db8af88389e4113c563d53b63d509

test:
  secret_key_base: 8ccf08a3d62a4f84badc3b19d9d73913ddff0ec9571f0142f15afbf3f095bcf2d5556eac45d4bc543267d401f530887126446fa222655ecbebae504ccb5e434d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
